---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/world_heritages":
    get:
      summary: list world_heritages
      responses:
        '200':
          description: successful
  "/api/v1/world_heritages/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show world_heritage
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
